[workspace]
authors = ["lnotspotl <lnotspotl@gmail.com>"]
channels = ["robostack-humble", "conda-forge"] # "robostack-staging", 
name = "tbai_ros2"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.1"

[target.unix.activation]
# For activation scripts, we use bash for Unix-like systems
scripts = ["../../install/setup.bash"]

# To build you can use - `pixi run -e <ros distro> build <Any other temporary args>`
[feature.all.target.unix.tasks]
build = "colcon build --symlink-install --cmake-args -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPython_FIND_VIRTUALENV=ONLY -DPython3_FIND_VIRTUALENV=ONLY"

[feature.common.dependencies]
cmake = "3.*"
gxx = ">=15.2.0,<15.3"
gcc = ">=15.2.0,<15.3"
yaml-cpp = ">=0.8.0,<0.9"
fmt = ">=11.2.0,<12"
spdlog = ">=1.15.3,<2"
pinocchio = ">=3.7.0,<4"
pytorch = "2.*"
eigen="3.4.0.*"

[feature.all.dependencies] 
ros-humble-desktop = ">=0.10.0,<0.11"
ros-humble-ament-cmake-auto = ">=1.3.12,<2"

[environments]
all-gpu-free = ["common", "all"]

[dependencies]
python = "3.*"
just = ">=1.43.0,<2"

# ros-humble-ament-cmake-auto = "1.3.2.*"
# cmake = "3.28.*"
# python = "3.9.*"
# gxx = ">=15.2.0,<15.3"
# gcc = ">=15.2.0,<15.3"
# yaml-cpp = ">=0.8.0,<0.9"
# fmt = ">=11.2.0,<12"
# spdlog = ">=1.16.0,<2"
# pinocchio = ">=3.7.0,<4"
# just = ">=1.43.0,<2"
# pytorch = ">=2.7.1,<3"
# pyparsing = ">=3.2.3,<4"
