[workspace]
authors = ["lnotspotl <lnotspotl@gmail.com>"]
channels = ["robostack-humble", "conda-forge"] # "robostack-staging", 
name = "tbai_ros2"
platforms = ["linux-64", "linux-aarch64"]
version = "0.0.1"

[feature.common.dependencies]

# tbai dependencies
gxx="*" # "13.3.0.*"
gcc="*" # "13.3.0.*"
fmt="*" # "10.2.1.*"
spdlog="*" # "1.13.0.*"
libtorch = { version = "==2.1.0", build = "*cpu_generic*" }
# cpp-argparse = "*"
# eigen="3.4.0.*"
# gtest="*"
# pybind11="2.13.6.*"
yaml-cpp="*"
pinocchio="*" # "2.7.*"
cmake="3.28.3.*"
# huggingface_hub = "*"
# catkin_tools = "*"
# make = "*"
# rosdep = "*"
# python="3.11.*"
# compilers = "*"
# pkg-config = "*"
# ninja = "*"

# [feature.go2.dependencies]
# pcl="*"
# ros-noetic-pcl-ros="*"
# ros-noetic-desktop="1.5.0.*"
# librealsense = ">=2.55.1,<3"

[feature.all.dependencies]
ros-humble-ament-cmake-auto = ">=1.3.2,<2"
# ros-noetic-desktop-full = "1.5.0.*"
# gazebo = "11.14.0.*"
# ros-distro-mutex = "0.5.0.*"
# libprotobuf = "*"
# colcon-common-extensions = "*"
# doxygen = "*"
# ros-noetic-ros-control = "*"
# ros-noetic-ros-controllers = "*"
# mpfr = "*"
# glpk = "*"
# ros-noetic-octomap-msgs = "*"
# librealsense = ">=2.55.1,<3"

# [feature.go2-gpu.dependencies]
# cuda-version = "11.4.*"
# cupy = "*"
# ros-noetic-image-transport = ">=1.12.0,<2"
# ros-noetic-image-transport-plugins = ">=1.14.0,<2"

# [feature.desktop-gpu.dependencies]
# cuda-version = "12.8.*"
# cupy = "*"
# ros-noetic-image-transport = ">=1.12.0,<2"
# ros-noetic-image-transport-plugins = ">=1.14.0,<2"

[environments]
# all = ["common", "all", "desktop-gpu"]
all-gpu-free = ["common", "all"]
# go2 = ["common", "go2", "go2-gpu"]
# go2-gpu-free = ["common", "go2"]

[dependencies]
python = "*" # ">=3.11.8,<3.14"
cpplint = "*" # ">=1.6.0,<2"
just = "*" # ">=1.42.4,<2"

[pypi-dependencies]
# simple-parsing = ">=0.1.7, <0.2"
# ruamel-yaml = ">=0.18.14, <0.19"
# shapely = ">=2.1.1, <3"
